### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Phantop** [PretendoNetwork/archival-tools#5]
Hey, there! I wanted to run the New Leaf dream backup tool, but I'm seemingly getting stuck on downloading offset 0. Nothing is being stored in the objects folder, even after a few minutes. Does this still work? If not, is there an archived backup of the dreams I could grab from anywhere?

**Comment by jonbarrow** [comment]
I can confirm this does still work. Sounds like a connection issue on your end. And yes, one of our team members @InternalLoss has an archive of ACNL already. Though I'm not sure if he's published it anywhere. We plan to upload all of our archives to the internet archive post shutdown

**Comment by cheater** [comment]
@jonbarrow @InternalLoss worth chiming in here to coordinate the effort

https://www.reddit.com/r/DataHoarder/comments/1bejk7e/super_mario_maker_servers_are_going_away_very/

**Comment by jonbarrow** [comment]
> @jonbarrow @InternalLoss worth chiming in here to coordinate the effort
> 
> [reddit.com/r/DataHoarder/comments/1bejk7e/super_mario_maker_servers_are_going_away_very](https://www.reddit.com/r/DataHoarder/comments/1bejk7e/super_mario_maker_servers_are_going_away_very/)

I've left a detailed reply to this post. There's quite a bit of incorrect information there

**Comment by cheater** [comment]
appreciated. Hopefully this will spur someone to write a new frontend to this and perhaps a proxy server to let WiiU and 3DS consoles still access that cloud data.

**Comment by jonbarrow** [comment]
> perhaps a proxy server to let WiiU and 3DS consoles still access that cloud data.

That's not how this works. You'd need an entirely custom SMM server for this. The game doesn't know where to download courses from on it's own. There's nothing to proxy. The game is told where to download data from via the game server. And if you're writing your own game server, like we do, you might as well just give the real download URLs

**Comment by cheater** [comment]
Oh yes, definitely, a full backend server is necessary, I agree. The proxy is just to intercept calls going out to the original servers (that will be down) and redirect them to new ones :)

The backend server could itself also source files from archive org directly. This way there wouldn't be a need to actually download the files. Or, from a torrent - and join the swarm to support it.
